export const FETCH_ARTIST_INFO_BEGIN    = 'FETCH_ARTIST_INFO_BEGIN';
export const FETCH_ARTIST_INFO_SUCCESS  = 'FETCH_ARTIST_INFO_SUCCESS';
export const FETCH_ARTIST_INFO_FAILURE  = 'FETCH_ARTIST_INFO_FAILURE';
export const FETCH_TRACKS_BEGIN    = 'FETCH_TRACKS_BEGIN';
export const FETCH_TRACKS_SUCCESS  = 'FETCH_TRACKS_SUCCESS';
export const FETCH_TRACKS_FAILURE  = 'FETCH_TRACKS_FAILURE';